; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=ppu -global-isel -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefix=RV32I %s

define void @foo() {
  ; RV32I-LABEL: foo
  ; RV32I:       # %bb.0: # %entry
  ; RV32I:         ret

entry:
  ret void
}
