; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=ppu -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefix=RV32I %s

declare i32 @llvm.flt.rounds()

define i32 @test_flt_rounds() nounwind {
; RV32I-LABEL: test_flt_rounds:
; RV32I:       # %bb.0:
; RV32I-NEXT:    addi a0, zero, 1
; RV32I-NEXT:    ret
;
  %1 = call i32 @llvm.flt.rounds()
  ret i32 %1
}
