; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=ppu -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefix=RV32I %s

define void @foo(i32 *%b, i32 %c) nounwind {
; RV32I-LABEL: foo:
; RV32I:       # %bb.0:
; RV32I-NEXT:    addi a2, zero, 1
; RV32I-NEXT:    bne a1, a2, .LBB0_2
; RV32I-NEXT:  # %bb.1: # %end1
; RV32I-NEXT:    sw zero, 0(a0)
; RV32I-NEXT:    ret
; RV32I-NEXT:  .LBB0_2: # %test2
; RV32I-NEXT:    sw a2, 0(a0)
; RV32I-NEXT:    ret
  %tst1 = icmp eq i32 %c, 1
  br i1 %tst1, label %end1, label %test2

test2:
  store i32 1, i32* %b
  ret void

end1:
  store i32 0, i32* %b
  ret void
}
