; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=ppu -mattr=+v -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=RV32IV

declare i32 @llvm.ppu.setvl(i32)
declare <vscale x 1 x i32> @llvm.ppu.vadd(<vscale x 1 x i32>, <vscale x 1 x i32>, i32)
declare <vscale x 1 x i32> @llvm.ppu.vlw(i32*)
declare i32 @llvm.ppu.vmpopcnt(<vscale x 1 x i32>, i32)
declare i32 @llvm.ppu.vmfirst(<vscale x 1 x i32>, i32)

; R[0..n] = A[0..n]
define i32 @foo(i32 %n, i32* %A) {
; RV32IV-LABEL: foo:
; RV32IV:       # %bb.0:
; RV32IV-NEXT:    vconfig 96
; RV32IV-NEXT:    vsetvl a0, a0
; RV32IV-NEXT:    vlw v0, 0(a1)
; RV32IV-NEXT:    vmfirst a0, v0
; RV32IV-NEXT:    vmpop a1, v0
; RV32IV-NEXT:    add a0, a1, a0
; RV32IV-NEXT:    vconfig 1
; RV32IV-NEXT:	.cfi_def_cfa_offset 0
; RV32IV-NEXT:    ret
	%vl = call i32 @llvm.ppu.setvl(i32 %n)
	%v.A = call <vscale x 1 x i32> @llvm.ppu.vlw(i32* %A)
	%popcnt = call i32 @llvm.ppu.vmpopcnt(<vscale x 1 x i32> %v.A, i32 %vl)
	%first = call i32 @llvm.ppu.vmfirst(<vscale x 1 x i32> %v.A, i32 %vl)
	%sum = add i32 %popcnt, %first
	ret i32 %sum
}
