; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py

; This test case is significantly simplified from the submitted .ll but
; demonstrates the same issue. At the time of this problem report, an infinite
; loop would be created in DAGCombine, converting ANY_EXTEND to SIGN_EXTEND
; and back again.

define signext i8 @foo(i32 %a, i32 %b) nounwind {
 %1 = lshr i32 %a, %b
 %2 = trunc i32 %1 to i8
 ret i8 %2
}
