; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=ppu -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefix=RV32I %s

declare void @llvm.prefetch(i8*, i32, i32, i32)

define void @test_prefetch(i8* %a) nounwind {
; RV32I-LABEL: test_prefetch:
; RV32I:       # %bb.0:
; RV32I-NEXT:    ret
;
  call void @llvm.prefetch(i8* %a, i32 0, i32 1, i32 2)
  ret void
}
